name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - tintin-dev
  workflow_dispatch:

jobs:
  test-sim:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:     [ubuntu-20.04]
        mode:   [newlib]
        target: [rv32gcv_zvfh-ilp32d, rv64gcv_zvfh-lp64d]
        sim:    [spike]
        cmodel: [medlow, medany]
    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: sudo ./.github/setup-apt.sh

      - name: clear space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: build toolchain
        run: |
          TARGET_TUPLE=($(echo ${{ matrix.target }} | tr "-" "\n"))
          ./configure --prefix=/opt/riscv --with-arch=${TARGET_TUPLE[0]} --with-abi=${TARGET_TUPLE[1]} --with-sim=${{ matrix.sim }} --with-cmodel=${{ matrix.cmodel }}
          make -j $(nproc) ${{ matrix.mode }}

      - name: make report
        run: make report-${{ matrix.mode }} -j $(nproc)
